version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: masjid_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: masjid_db
    ports:
      - "5437:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data

volumes:
  postgres_data_new:

